# Introduction: The current docker-compose file is version 1. Let us upgrade it to version 3.
# Instruction: First, add a version property to the beginning of the file and update it with a value of '3'.
# ------------------------------
#           BEFORE
# ------------------------------
#redis:
#  image: redis
#
#db:
#  image: postgres:9.4
#
#vote:
#  image: voting-app
#  ports:
#    - "5000:80"
#  links:
#    - redis
#
#result:
#  image: worker-app
#  ports:
#      - 5000:80
#  links:
#      - db
#
#worker:
#  image: result-app
#  links:
#      - redis
#      - db


# ------------------------------
#           AFTER
# ------------------------------
version: '3'
redis:
  image: redis

db:
  image: postgres:9.4

vote:
  image: voting-app
  ports:
    - "5000:80"
  links:
    - redis

result:
  image: worker-app
  ports:
      - 5000:80
  links:
      - db

worker:
  image: result-app
  links:
      - redis
      - db
